apiVersion: v1
kind: Secret
metadata:
  name: smoke-db-auth
  namespace: sidecarless-smoke
  labels:
    app.kubernetes.io/part-of: sidecarless-poc
type: Opaque
stringData:
  POSTGRES_DB: smoke
  POSTGRES_USER: smoke
  POSTGRES_PASSWORD: smoke-password
