apiVersion: v1
kind: Namespace
metadata:
  name: sidecarless-observability
  labels:
    app.kubernetes.io/part-of: sidecarless-poc
---
apiVersion: v1
kind: Namespace
metadata:
  name: sidecarless-demo
  labels:
    app.kubernetes.io/part-of: sidecarless-poc
